version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0@sha256:8192e949e2d5d02be195f96afef1cf30adc87a4d5e631895497e11f4acc7a429
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
